version: '3'

services:

  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - database
    environment:
      - PORT=4000
      - DATABASE_CONN=mongodb://database:27017/surreal-estate
      

  database:
    image: mongo
